//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Rental_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentalInfo
    {
        public int customerId { get; set; }
        public string customerName { get; set; }
        public Nullable<decimal> cost { get; set; }
        public Nullable<System.DateTime> dateRented { get; set; }
        public Nullable<System.DateTime> dateReturned { get; set; }
        public Nullable<int> carId { get; set; }
    
        public virtual typeOfCar typeOfCar { get; set; }
    }
}
